import { a as patchEsm, b as bootstrapLazy } from './core-f05d0500.js';

const defineCustomElements = (win, options) => {
  return patchEsm().then(() => {
    bootstrapLazy([["fw-timepicker",[[1,"fw-timepicker",{"hourFormat":[1,"hour-format"],"timeValue":[1025,"time-value"],"interval":[2],"minTime":[1,"min-time"],"maxTime":[1,"max-time"],"timeValues":[32],"isMeridianFormat":[32],"minTimeObj":[32],"maxTimeObj":[32]}]]],["fw-input",[[1,"fw-input",{"label":[1],"value":[1025],"type":[1],"autocomplete":[1],"clearInput":[4,"clear-input"],"maxlength":[2],"minlength":[2],"name":[1],"placeholder":[1],"state":[1],"stateText":[1,"state-text"],"readonly":[4],"required":[4],"disabled":[4],"iconLeft":[1,"icon-left"],"iconRight":[1,"icon-right"],"hasFocus":[32],"setFocus":[64]}]]],["fw-button",[[1,"fw-button",{"type":[1],"color":[1],"disabled":[516],"expand":[4],"size":[1]}]]],["fw-checkbox",[[1,"fw-checkbox",{"checked":[1028],"disabled":[1028],"label":[1],"value":[1]}]]],["fw-label",[[1,"fw-label",{"color":[1],"value":[1]}]]],["fw-radio",[[1,"fw-radio",{"checked":[1028],"disabled":[1028],"label":[1],"value":[1],"name":[1]}]]],["fw-radio-group",[[0,"fw-radio-group",{"allowEmpty":[4,"allow-empty"],"name":[1],"value":[1032]}]]],["fw-spinner",[[1,"fw-spinner",{"size":[1],"color":[1]}]]],["fw-tab",[[1,"fw-tab",{"title":[1],"message":[1]}]]],["fw-tabs",[[1,"fw-tabs",{"tabs":[32],"activeTabIndex":[32],"activeChildClass":[32]},[[0,"click","toggelLink"],[0,"click","addClassToTabContainer"]]]]],["fw-textarea",[[1,"fw-textarea",{"label":[1],"value":[1025],"cols":[2],"rows":[2],"maxlength":[2],"minlength":[2],"name":[1],"placeholder":[1],"state":[1],"wrap":[1],"stateText":[1,"state-text"],"readonly":[4],"required":[4],"disabled":[4],"hasFocus":[32],"setFocus":[64]}]]],["fw-toggle",[[1,"fw-toggle",{"state":[4],"size":[1],"name":[1],"disabled":[4]}]]],["fw-select",[[1,"fw-select",{"label":[1],"value":[1032],"name":[1],"type":[1],"placeholder":[1],"state":[1],"stateText":[1,"state-text"],"readonly":[4],"required":[4],"forceSelect":[4,"force-select"],"disabled":[4],"multiple":[4],"isExpanded":[32],"options":[32],"filteredOptions":[32],"hasFocus":[32],"getSelectedItem":[64]},[[0,"fwSelected","fwSelectedHandler"],[0,"fwClosed","fwCloseHandler"],[0,"keydown","onKeyDonw"]]]]],["fw-icon",[[1,"fw-icon",{"name":[1],"size":[2],"color":[1],"svgHTML":[32]}]]],["fw-select-option_2",[[1,"fw-select-option",{"value":[513],"selected":[1540]}],[1,"fw-tag",{"text":[513],"value":[513]}]]]], options);
  });
};

export { defineCustomElements };
